version: '3.3'

services:

  paymybuddy-backend:
    image: paymybuddy-backend
    container_name: paymybuddy-backend
    depends_on:
      - paymybuddy-db
    ports:
      - "8080:8080"
    env_file:
      - ./secrets/app.env
    networks:
      - paymybuddy_network
   
  paymybuddy-db:
    image: mysql:8
    container_name: paymybuddy-db
    volumes:
      - ./initdb/create.sql:/docker-entrypoint-initdb.d/init.sql
      - paymybuddy-data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./secrets/db.env
    networks:
      - paymybuddy_network
  
networks:
  paymybuddy_network:
    name: paymybuddy_network
    driver: bridge

volumes:
  paymybuddy-data:
